In [ ]:
import numpy as np

In [ ]:
A=np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
A=np.arange(1,13).reshape(3,4)
B=np.linspace(21,13,39)
print(A)
print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[21.         20.78947368 20.57894737 20.36842105 20.15789474 19.94736842
 19.73684211 19.52631579 19.31578947 19.10526316 18.89473684 18.68421053
 18.47368421 18.26315789 18.05263158 17.84210526 17.63157895 17.42105263
 17.21052632 17.         16.78947368 16.57894737 16.36842105 16.15789474
 15.94736842 15.73684211 15.52631579 15.31578947 15.10526316 14.89473684
 14.68421053 14.47368421 14.26315789 14.05263158 13.84210526 13.63157895
 13.42105263 13.21052632 13.        ]


In [ ]:
B=np.array([1,13,11,24,23,58,100,78])
B.resize(2,2,2)

print(B)

[[[  1  13]
  [ 11  24]]

 [[ 23  58]
  [100  78]]]


In [ ]:
B=np.array([1,13,11,24,23,58,100,78])
B.resize(2,2,2)#Changes the shape of the original array
#re-shape-changes needs saving in another variable
print(B)

[[[  1  13]
  [ 11  24]]

 [[ 23  58]
  [100  78]]]


In [ ]:
A=np.array([24,11,37,49])
B=np.array([23,10,33,23])#list will throw an error while arrays iterate themselves...
c=A-B
print(c)

[ 1  1  4 26]


In [ ]:
A=np.array([24,11,37,49]).reshape(2,2)
B=np.array([23,10,33,23]).reshape(2,2)
print(A)
print("_______________________________")
print(B)
print("_______________________________")
c=A*B
print(c)


[[24 11]
 [37 49]]
_______________________________
[[23 10]
 [33 23]]
_______________________________
[[ 552  110]
 [1221 1127]]


In [ ]:
A=np.array([24,11,37,49])
print(A.max())
print(A.min())

49
11


In [ ]:
A=np.array([24,11,37,49]).reshape(2,2)
B=np.array([23,10,33,23]).reshape(2,2)
print(A)
print("_______________________________")
print(B)
print("_______________________________")
c=A@B
print(c)

[[24 11]
 [37 49]]
_______________________________
[[23 10]
 [33 23]]
_______________________________
[[ 915  493]
 [2468 1497]]


In [ ]:
A=np.array([24,11,37,49,'67','98',107,78])#max and min values accepts only for int,float values
print(A.max())
B=np.array([24,11,37,49,'67','98',107,78])#max and min values accepts only for int,float values
print(B.max())
C=np.array([24,11,37,49,67,98,107,78])
print(C.max())



In [ ]:
A=np.array([24,11,37,49,67,72,67,78]).reshape(2,4)
print(A)
print(A.max(axis=0))  #axis=0 column
print("___________")
print(A.max(axis=1))  #axis=1  rows


[[24 11 37 49]
 [67 72 67 78]]
[67 72 67 78]
___________
[49 78]


In [ ]:
A=np.array([24,11,37,49,67,72,67,78]).reshape(2,4)
print(A)
print(A.min(axis=0))   #axis=0 column
print("___________")
print(A.min(axis=1))    #axis=1  rows

[[24 11 37 49]
 [67 72 67 78]]
[24 11 37 49]
___________
[11 67]


In [ ]:
#joining arrays
A=np.array([24,11,37,49,67,72,67,89,12,88]).reshape(2,5)
B=np.array([1,3,5,7,9,11,13,15,17,25]).reshape(2,5)
print(A)
print("-----------")
print(B)
print("-----------")
print("After Joining horizantal stack")
print(np.vstack((A,B)))



[[24 11 37 49 67]
 [72 67 89 12 88]]
-----------
[[ 1  3  5  7  9]
 [11 13 15 17 25]]
-----------
After Joining horizantal stack
[[24 11 37 49 67]
 [72 67 89 12 88]
 [ 1  3  5  7  9]
 [11 13 15 17 25]]


In [ ]:
A=np.array([24,11,37,49,67,72,67,89,12,88]).reshape(2,5)
B=np.array([1,3,5,7,9,11,13,15,17,25]).reshape(2,5)
print(A)
print("-----------")
print(B)
print("-----------")
print("After Joining horizantal stack")
print(np.hstack((A,B)))


[[24 11 37 49 67]
 [72 67 89 12 88]]
-----------
[[ 1  3  5  7  9]
 [11 13 15 17 25]]
-----------
After Joining horizantal stack
[[24 11 37 49 67  1  3  5  7  9]
 [72 67 89 12 88 11 13 15 17 25]]


In [ ]:
A=np.arange(30).reshape(2,3,5)
print(A)
print("After dstack")
print(np.dstack(A))#no. of rows --> no.of columns
                   #no. of col in every grp --> no. of rows in every grp
                   [0,0],[1,1].....

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#splitting arrays
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
print(np.vsplit(A,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]


In [ ]:
#splitting arrays
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.vsplit(A,(2,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#splitting arrays
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.hsplit(A,(2,5))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13],
        [15, 16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([], shape=(6, 0), dtype=int64)]

In [ ]:
#splitting arrays
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.hsplit(A,(2,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13],
        [15, 16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([], shape=(6, 0), dtype=int64)]

In [ ]:
A=np.arange(10).reshape(2,5)
print(A)
print(A.argmax())

[[0 1 2 3 4]
 [5 6 7 8 9]]
9


In [ ]:
A=np.linspace(17,4,18).reshape(3,6)
print(A)
print(A.argmax())

[[17.         16.23529412 15.47058824 14.70588235 13.94117647 13.17647059]
 [12.41176471 11.64705882 10.88235294 10.11764706  9.35294118  8.58823529]
 [ 7.82352941  7.05882353  6.29411765  5.52941176  4.76470588  4.        ]]
0


In [ ]:
A=np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)
print(A)
print(A.argmax())

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
6


In [ ]:
A=np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)
print(A)
print(A.argmax(axis=0))# axis=0 ->[0 0 0]  #axis=1 -> [0,1,2,3]
                                  [1 1 1]             [0 1 2 3]
                                   [2 2 2]            [0 1 2 3]

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
[2 2 1 0]


In [ ]:
A=np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)
print(A)
print(A.argmax(axis=1))

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
[3 2 1]


In [ ]:
A=np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)
print(A)
print(A.argmin())

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
1


In [ ]:
A=np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)
print(A)
print(A.argmin(axis=0))

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
[1 0 2 2]


In [ ]:
A=np.array([17,4,18,56,12,33,89,21,34,55,11,13]).reshape(3,4)
print(A)
print(A.argmin(axis=1))

[[17  4 18 56]
 [12 33 89 21]
 [34 55 11 13]]
[1 0 2]


STATISTICS


In [ ]:
A=np.array([12,34,25,66,71,88])
print("Mean:",np.mean(A))
print("Median:",np.median(A))
print("Variance:",np.var(A))
print("Standard deviation:",np.std(A))

Mean: 49.333333333333336
Median: 50.0
Variance: 743.888888888889
Standard deviation: 27.274326552435515


TRIGONOMETRY


In [ ]:
A=np.pi
print(A)#radians


3.141592653589793


In [ ]:
np.rad2deg(A)

180.0

In [ ]:
B=[np.pi/4,np.pi/3,np.pi/2,np.pi/1]
print(B)

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]


In [ ]:
print(np.rad2deg(B))

[ 45.  60.  90. 180.]


In [ ]:
C=np.array([0,30,45,60,90,120,180])
D=np.deg2rad(C)
print(D)

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
np.sin(C)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [ ]:
np.cos(C)

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
np.tan(C)

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
np.arcsin(1) #sin^-1

1.5707963267948966

In [ ]:
np.arccos(1) #cos^-1

0.0

In [ ]:
np.arctan(1)#tan^-1

0.7853981633974483

In [ ]:
a=6
b=4
print(np.hypot(a,b))#hyptenuse

7.211102550927978


# Searching!

In [ ]:
A=np.array([90,3,45,21,34,90,21])
print(np.where(A==21))

(array([3, 6]),)


In [ ]:
A=np.array([90,3,45,21,34,90,21])
print(np.where(A%2==0))

(array([0, 4, 5]),)


In [ ]:
A=np.array([90,3,45,21,34,90,21])
print(np.where(A>5))

(array([0, 2, 3, 4, 5, 6]),)


In [97]:
A=np.array([90,3,54,7,62,87])
print(np.searchsorted(A,54))

4


Linear Algebra and **ufunc**

In [98]:
A=np.array([6,24,60,12,18])
B=np.array([4,78,34,66,5])
print(np.add(A,B))
print(np.subtract(A,B))

[ 10 102  94  78  23]
[  2 -54  26 -54  13]


In [99]:
print(np.mod(A,B))
print(np.divide(A,B))
print(np.divmod(A,B))

[ 2 24 26 12  3]
[1.5        0.30769231 1.76470588 0.18181818 3.6       ]
(array([1, 0, 1, 0, 3]), array([ 2, 24, 26, 12,  3]))


In [101]:
A=np.array([6,24,60,12,18])
print(np.sort(A))

[ 6 12 18 24 60]


In [102]:
print(np.diff(A))

[ 18  36 -48   6]


In [104]:
A=np.array([6,24,60,12,18])
B=np.array([4,78,34,66,5])
print(np.union1d(A,B))

[ 4  5  6 12 18 24 34 60 66 78]


In [105]:
A=np.array([6,24,60,12,18])
B=np.array([4,78,34,66,5])
print(np.setdiff1d(A,B))

[ 6 12 18 24 60]


In [107]:
A=np.array([6,24,60,12,18])
B=np.array([4,24,6,78,34,66,5])
print(np.intersect1d(A,B))

[ 6 24]


Rounding

In [108]:
A=np.fix([-3.166,3.666])
print(A)

[-3.  3.]


In [109]:
A=np.trunc([-3.166,3.666])
print(A)

[-3.  3.]


In [110]:
A=np.around([-3.166,3.666])
print(A)

[-3.  4.]


In [111]:
A=np.floor([-3.166,3.666])
print(A)

[-4.  3.]


In [112]:
A=np.ceil([-3.166,3.666])
print(A)

[-3.  4.]


More Fuctions

In [113]:
A=np.array([23,45,67,89,10])
print(np.cumsum(A))

[ 23  68 135 224 234]


In [114]:
A=np.array([23,45,67,89,10])
print(np.cumprod(A))

[      23     1035    69345  6171705 61717050]


In [116]:
print(np.lcm(34,24))
print(np.gcd(34,24))

408
2


In [117]:
A=np.array([45,65,30])
print(np.lcm.reduce(A))

1170


In [118]:
A=np.array([45,65,30])
print(np.gcd.reduce(A))

5


In [120]:
#liner algebra /inverse matrix
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


Random

In [121]:
from numpy import random as rd

In [122]:
A=rd.rand()#n #default limit 0 to 0.99
print(A)

0.08885612982947011


In [127]:
A=rd.rand(10)
print(A)

[0.47393019 0.09920786 0.77885316 0.09323734 0.32096314 0.07197967
 0.66488055 0.43173537 0.06394355 0.33177596]


In [126]:
A=rd.randint(4) #limit
print(A)

1


In [128]:
A=rd.randint(50,size=6)
print(A)

[35 22 26  2 27 15]


In [129]:
A=rd.randint(50,size=(2,3))
print(A)

[[44 41 32]
 [39  7  8]]


Joins!

In [131]:
A=np.array([1,2,3])
B=np.array([4,5,6])
#1X4 ,2X5 ,3X6
print(np.inner(A,B))


32


In [132]:
A=np.array([1,2,3])
B=np.array([4,5,6])
#1X(4,5,6) ,2X(4,5,6) ,3X(4,5,6)
print(np.outer(A,B))


[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [133]:
A=np.array([1,2,3])
B=np.array([4,5,6])
#1X4 + 2X5 + 3X6
print(np.cross(A,B))


[-3  6 -3]


In [135]:
A=np.array([1,2,3])
B=np.array([4,5,6])
#1X4 ,2X5 ,3X6
print(np.outer(B,A))


[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
