In [ ]:
#variable
a=10
print("I am ",a,"years old")

I am  10 years old


In [ ]:
#Arthematic  operators
a=int(input("enter the a value"))
b=int(input("enter the b value"))
print("The sum is",a+b)
print("The diff is",b-a)
print("The mul is",a*b)
print("The quotient is",a/b)
print("The remainder is",a%b)
print("power of a to b",a**b)
print("The floor is",a//b)


enter the a value123
enter the b value345
The sum is 468
The diff is 222
The mul is 42435
The quotient is 0.3565217391304348
The remainder is 123
power of a to b 10405511812952707739731492191909310279808963525498753701928217916474886385941052560140442748734227867004377264381193268849497642332674520853680856731955339453782182000778572151915790183661428467128191156971185624751935558289235984940694575565357994647339478839262837633763628658085954923398402686359044635713314379871020068920843439705539639865845542678396366997528225532901486943708850217594261505335374752382964791075336794926116981773941103271997692404273885620938767016939887541682816056715874460198070088979100602619116772941858954918892595612021144861019975790300211490229075108891680089852245938818504839824260547929975904862425499924981169864416389299692481118813598785342001910981692356232252220864017249850782043
The floor is 0


In [ ]:
#Take the number from the user which is salary.if the salary is more than 50000 there is a 10% tax and print his final salary.
a=int(input("Enter the n value"))
if (a>50000):
  b=(10/100)*a

  print(b)
else:
  print("No tax Deduction")


Enter the n value45000
No tax Deduction


In [ ]:
#Get the salary from the user .If the salary is more than equal to 50000 apply 10%tax deduction.If the salary is < 50000 apply 5% tax.If the salary is more than 70000 apply 12% tax.If the salary exceeds 100000 print you are promoted to next level...
a=int(input("Enter the amount"))
if (a>0 and a<=50000):
  b=a-((5/100)*a)
  print(b)
elif(a>50000 and a<70000):
  c=a-((5/100)*a)
  print(c)
elif(a>70000 and a<100000):
  d=a-((12/100)*a)
  print(d)
else:
  print("You are promoted")




Enter the amount1000000
You are promoted


In [ ]:
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#Multiplication table using for loop
a=int(input("Enter n value"))
for i in range(1,11):

  print(a, 'x', i, '=', a*i)



Enter n value23
23 x 1 = 23
23 x 2 = 46
23 x 3 = 69
23 x 4 = 92
23 x 5 = 115
23 x 6 = 138
23 x 7 = 161
23 x 8 = 184
23 x 9 = 207
23 x 10 = 230


In [ ]:
#Multiplication table using While loop
n = int(input("Enter the number :"));
i = 1
while i < 11:
 b = n * i
 print(n," * ",i," = ",b)
 i = i + 1


Enter the number :13
13  *  1  =  13
13  *  2  =  26
13  *  3  =  39
13  *  4  =  52
13  *  5  =  65
13  *  6  =  78
13  *  7  =  91
13  *  8  =  104
13  *  9  =  117
13  *  10  =  130


In [ ]:
#lists
l1=[2,'valli',24]
print(l1)
n = int(input("Enter any Number  :"));
i = 1
while i < 11:
 value = n * i
 print(n," * ",i," = ",value)
 i = i + 1
Output

l1.insert(2,"Inserted")
print(l1)
l2=['murali',11,'krishna']
l1.extend(l2)
print(l1)
l1.pop(0)
print(l1)
l3=[1,'kill',89,'chat',9.1,'True']
l3.pop(2)
print(l3)
l3.remove('kill')
print(l3)
l3.clear()
print(l3)

[2, 'valli', 24]
[2, 'valli', 24, 'appended']
[2, 'valli', 'Inserted', 24, 'appended']
[2, 'valli', 'Inserted', 24, 'appended', 'murali', 11, 'krishna']
['valli', 'Inserted', 24, 'appended', 'murali', 11, 'krishna']
[1, 'kill', 'chat', 9.1, 'True']
[1, 'chat', 9.1, 'True']
[]


In [ ]:
#create a list of  10 integer elements and print their squares and save it in a new list
l=[1,2,3,4,5,6,7,8,9,10]

ele=[]
for i in l:
  ele.append(i*i)
print(ele)



[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
#List comprehension
#new list =(output for)
l=[1,2,3,4,5]
res=[i*i for i in l]
print(res)

[1, 4, 9, 16, 25]


In [ ]:
#Lc
#new list=(output for if)
l1=[23,67,12,34,69]
res=[i*i for i in l1 if i>50]
print (res)


[4489, 4761]


In [ ]:
#Lc
#new list=((st of if) if (cond) else (st of else) for)
l1=[23,67,12,34,69]
res=[i*i  if i>50 else 'x' for i in l1]
print (res)

['x', 4489, 'x', 'x', 4761]


In [ ]:
#Take the salary from the user if salary is < 50k then 10%tax otherwise 15% tax
sal=int(input("Enter n value"))
res=[ sal-sal*0.1  if sal < 50000  else sal-sal*0.15  for sal in l1]
print(res)

Enter n value45000
[]


In [ ]:
list=[78000,50400,34000,23000,14000]
res=[ i-i*0.1  if i < 50000  else i-i*0.15  for i in list]
print(res)

[66300.0, 42840.0, 30600.0, 20700.0, 12600.0]


In [ ]:
#Dictonaries
d={"Mentor":'Jwalitha',34:'Likitha',35:'Ramya',58:'Jahnavi'}
print(d)

{'Mentor': 'Jwalitha', 34: 'Likitha', 35: 'Ramya', 58: 'Jahnavi'}


In [ ]:
d={"Mentor":'Jwalitha',34:'Likitha',35:'Ramya',58:'Jahnavi'}
print(d.keys())


dict_keys(['Mentor', 34, 35, 58])


In [ ]:
d={"Mentor":'Jwalitha',34:'Likitha',35:'Ramya',58:'Jahnavi'}
print(d.values())

dict_values(['Jwalitha', 'Likitha', 'Ramya', 'Jahnavi'])


In [ ]:
print(d[58])

Jahnavi


In [ ]:
d1={"Dept":"CSE","details":{ "Year":"II","sec":"D","Count":71}}
print(d1)
print(d1['details']['Year'])
print(d1['details']['sec'])
print(d1['details']['Count'])

{'Dept': 'CSE', 'details': {'Year': 'II', 'sec': 'D', 'Count': 71}}
II
D
71


In [ ]:
val=[34,56,78,39,100]
names=['joe','suji','valli','krishna','ammu']
new_zip=zip(val,names)
for i in new_zip:
  print(i)

(34, 'joe')
(56, 'suji')
(78, 'valli')
(39, 'krishna')
(100, 'ammu')


In [ ]:
new_dict=zip(val,names)
for i in new_zip:
  print(new_dict)

In [ ]:
#Numpy
import numpy as np
A=np.array([1,2,3,4])#1d array
print(A.ndim)
print(A.shape)

1
(4,)


In [ ]:
#Numpy 2d array
import numpy as np
A=np.array([[1,2,3,4,],[5,6,7,8]])#2d array
#elements in each row =columns
print(A.ndim)
print(A.shape)
print(A)

2
(2, 4)
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
#Numpy 3d array
import numpy as np
A=np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])#3d array
#elements in each row =columns
print(A.ndim)
print(A.shape)
print(A)


2
(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np
A=np.array([[[1,2,3,4,],[5,6,7,8]],[[9,10,11,12],[2,3,4,7]]])#3d array
#elements in each row =columns
print(A.ndim)
print(A.shape)
print(A)


3
(2, 2, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [ 2  3  4  7]]]


In [ ]:
A=np.ones((2,4,3))#g,r,c
print(A)
B=np.zeros((2,4,3))#g,r,c
print(B)


[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
#Identity matrix
A=np.eye(4)
print(A)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A=np.arange(1,10,2)#start,stop,step
print(A)
print(type(A))


[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all numbers that are divisible by 8 using arange function between 1 to 1000
A=np.arange(8,1001,8)
print(A)


[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
#Splitting a range into n numbers with comman differences
A=np.linspace(48,59,12)
print(A)

[48. 49. 50. 51. 52. 53. 54. 55. 56. 57. 58. 59.]


In [ ]:
#Tuple,sets,generate qr code

In [2]:
#insertion to set
s={"Hello","Hi","Sai"}
print(s)
len(s)


{'Sai', 'Hello', 'Hi'}


3

In [ ]:
#insertion to set
s={"Hello","Hi", "Monday" "Sai" " Tuesday"}
print(s)
len(s)
